### ISSUE TITLE
Application crash on data connectivity drop

### ISSUE THREAD

**Issue by XBigTK13X** [XBigTK13X/snowgloo#10]
I was driving around connected to the VPN playing some music. Half way through a track, the audio stopped. I tried selecting other songs, next, forward, etc and nothing would play. I might have driven through a dead zone.

An error was logged to the server, which is posted below.

`
1582742876233 - 2020/02/26 12:47:56 - Util : An error occurred null => java.lang.IllegalStateException at android.media.MediaPlayer.getDuration(Native Method) at com.simplepathstudios.snowgloo.audio.LocalPlayer.getSongDuration(LocalPlayer.java:122) at com.simplepathstudios.snowgloo.audio.AudioPlayer.getSongDuration(AudioPlayer.java:130) at com.simplepathstudios.snowgloo.MainActivity$11.run(MainActivity.java:297) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:214) at android.app.ActivityThread.main(ActivityThread.java:6986) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
`

**Comment by XBigTK13X** [comment]
Here's more info from logcat

```
02-10 12:35:11.581 14195 14195 E AndroidRuntime: FATAL EXCEPTION: main
02-10 12:35:11.581 14195 14195 E AndroidRuntime: Process: com.simplepathstudios.snowgloo, PID: 14195
02-10 12:35:11.581 14195 14195 E AndroidRuntime: java.lang.IllegalStateException
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at android.media.MediaPlayer.getDuration(Native Method)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at com.simplepathstudios.snowgloo.audio.LocalPlayer.getSongDuration(LocalPlayer.java:122)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at com.simplepathstudios.snowgloo.audio.AudioPlayer.getSongDuration(AudioPlayer.java:129)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at com.simplepathstudios.snowgloo.MainActivity$10.run(MainActivity.java:236)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-10 12:35:11.581 14195 14195 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: FATAL EXCEPTION: main
02-10 15:16:19.623 30207 30207 E AndroidRuntime: Process: com.simplepathstudios.snowgloo, PID: 30207
02-10 15:16:19.623 30207 30207 E AndroidRuntime: java.lang.IllegalStateException
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at android.media.MediaPlayer.getDuration(Native Method)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at com.simplepathstudios.snowgloo.audio.LocalPlayer.getSongDuration(LocalPlayer.java:122)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at com.simplepathstudios.snowgloo.audio.AudioPlayer.getSongDuration(AudioPlayer.java:129)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at com.simplepathstudios.snowgloo.MainActivity$10.run(MainActivity.java:236)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
02-10 15:16:19.623 30207 30207 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
