### ISSUE TITLE
Service doesn't properly launch when resuming app

### ISSUE THREAD

**Issue by XBigTK13X** [XBigTK13X/snowgloo#16]
```
1584296296152 - 2020/03/15 13:18:16 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord
com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{
com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1855) at 
android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214) 
at android.app.ActivityThread.main(ActivityThread.java:6986)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
```

**Comment by XBigTK13X** [comment]
This supposedly has something to do with notifications and background services.

https://stackoverflow.com/questions/44425584/context-startforegroundservice-did-not-then-call-service-startforeground

https://issuetracker.google.com/issues/76112072#comment56

**Comment by XBigTK13X** [comment]
This might be due to Samsung's battery optimization. I'm going to try running with that off and see if the error goes away.

**Comment by XBigTK13X** [comment]
Another crash today

```
1608504560028 - 2020/12/20 16:49:20 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f357de7 u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f357de7 u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
```

**Comment by XBigTK13X** [comment]
Had this happen when hitting "Next" button on bottom audio controls.

```
1611936042244 - 2021/01/29 10:00:42 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1475a1a u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1475a1a u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
```

**Comment by XBigTK13X** [comment]
```
1618760705107 - 2021/04/18 10:45:05 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2f81e u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2f81e u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8425) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

1618760686047 - 2021/04/18 10:44:46 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f31ab0d u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f31ab0d u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:246) at android.app.ActivityThread.main(ActivityThread.java:8425) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

**Comment by XBigTK13X** [comment]
```
1628289714961 - 2021/08/06 17:41:54 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b0a7a44 u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b0a7a44 u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

1628289202653 - 2021/08/06 17:33:22 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{661ad1f u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{661ad1f u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

1628288345794 - 2021/08/06 17:19:05 - Util : An error occurred Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b0409ad u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} => android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{b0409ad u0 com.simplepathstudios.snowgloo/com.google.android.gms.cast.framework.media.MediaNotificationService} at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

1627928125167 - 2021/08/02 13:15:25 - Util : An error occurred Unable to instantiate receiver com.simplepathstudios.snowgloo.SnowglooService: java.lang.ClassCastException: com.simplepathstudios.snowgloo.SnowglooService cannot be cast to android.content.BroadcastReceiver => java.lang.RuntimeException: Unable to instantiate receiver com.simplepathstudios.snowgloo.SnowglooService: java.lang.ClassCastException: com.simplepathstudios.snowgloo.SnowglooService cannot be cast to android.content.BroadcastReceiver at android.app.ActivityThread.handleReceiver(ActivityThread.java:4200) at android.app.ActivityThread.access$1700(ActivityThread.java:274) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) Caused by: java.lang.ClassCastException: com.simplepathstudios.snowgloo.SnowglooService cannot be cast to android.content.BroadcastReceiver at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110) at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:54) at android.app.ActivityThread.handleReceiver(ActivityThread.java:4193) ... 8 more

1627928120075 - 2021/08/02 13:15:20 - Util : An error occurred Unable to instantiate receiver com.simplepathstudios.snowgloo.SnowglooService: java.lang.ClassCastException: com.simplepathstudios.snowgloo.SnowglooService cannot be cast to android.content.BroadcastReceiver => java.lang.RuntimeException: Unable to instantiate receiver com.simplepathstudios.snowgloo.SnowglooService: java.lang.ClassCastException: com.simplepathstudios.snowgloo.SnowglooService cannot be cast to android.content.BroadcastReceiver at android.app.ActivityThread.handleReceiver(ActivityThread.java:4200) at android.app.ActivityThread.access$1700(ActivityThread.java:274) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:8167) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) Caused by: java.lang.ClassCastException: com.simplepathstudios.snowgloo.SnowglooService cannot be cast to android.content.BroadcastReceiver at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110) at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:54) at android.app.ActivityThread.handleReceiver(ActivityThread.java:4193) ... 8 more 
```

**Comment by XBigTK13X** [comment]
Haven't had this issue on a Pixel 7. Seemed to go away on an S10e by disabling all optimizations.
