### ISSUE TITLE
Cast errors when closing the app

### ISSUE THREAD

**Issue by XBigTK13X** [XBigTK13X/snowgloo#25]
```
1592077755470 - 2020/06/13 14:49:15 - MainActivity : ====== Starting new app instance ======

1592077754030 - 2020/06/13 14:49:14 - SnowglooService : Cast session changed state to NO_DEVICES_AVAILABLE

1592077754027 - 2020/06/13 14:49:14 - AudioPlayer : Launching with the local player

1592077754026 - 2020/06/13 14:49:14 - CastPlayer : isCasting is false

1592077754024 - 2020/06/13 14:49:14 - AudioPlayer : Destroying the audio players

1592077754020 - 2020/06/13 14:49:14 - AudioPlayer : Destroying the audio players

1592077754020 - 2020/06/13 14:49:14 - SnowglooService : Swiped away from the recents menu, close the activity

1592077753948 - 2020/06/13 14:49:13 - AudioPlayer : Message: Attempt to invoke interface method 'void com.simplepathstudios.snowgloo.audio.IAudioPlayer.play(com.simplepathstudios.snowgloo.api.model.MusicFile, int)' on a null object reference StackTrace: java.lang.NullPointerException: Attempt to invoke interface method 'void com.simplepathstudios.snowgloo.audio.IAudioPlayer.play(com.simplepathstudios.snowgloo.api.model.MusicFile, int)' on a null object reference at com.simplepathstudios.snowgloo.audio.AudioPlayer.setPlaybackMode(AudioPlayer.java:99) at com.simplepathstudios.snowgloo.SnowglooService$1.onCastStateChanged(SnowglooService.java:50) at com.google.android.gms.cast.framework.zze.onCastStateChanged(Unknown Source:6) at com.google.android.gms.cast.framework.zzn.dispatchTransaction(Unknown Source:13) at com.google.android.gms.internal.cast.zza.onTransact(Unknown Source:13) at android.os.Binder.transact(Binder.java:914) at kw.b(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):2) at sa.a(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):0) at ta.a(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):5) at ta.e(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):3) at sy.a(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):15) at ta.a(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):75) at sk.a(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):4) at kx.onTransact(:com.google.android.gms.dynamite_dynamitemodulesc@202115081@20.21.15 (120400-0):4) at android.os.Binder.transact(Binder.java:914) at com.google.android.gms.internal.cast.zzb.zzb(Unknown Source:20) at com.google.android.gms.cast.framework.zzv.zza(Unknown Source:27) at com.google.android.gms.cast.framework.SessionManager.endCurrentSession(Unknown Source:18) at com.simplepathstudios.snowgloo.audio.CastPlayer.destroy(CastPlayer.java:190) at com.simplepathstudios.snowgloo.audio.AudioPlayer.destroy(AudioPlayer.java:259) at com.simplepathstudios.snowgloo.MainActivity.onDestroy(MainActivity.java:395) at android.app.Activity.performDestroy(Activity.java:8217) at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342) at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5178) at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5227) at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237) at android.app.ActivityThread.main(ActivityThread.java:7811) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

1592077753946 - 2020/06/13 14:49:13 - AudioPlayer : Attempting to resume playback after swapping mode

1592077753945 - 2020/06/13 14:49:13 - AudioPlayer : Playback in progress on remote, pausing

1592077753946 - 2020/06/13 14:49:13 - CastPlayer : pause

1592077753945 - 2020/06/13 14:49:13 - AudioPlayer : Playback mode changed to LOCAL

1592077753945 - 2020/06/13 14:49:13 - SnowglooService : Cast session changed state to NOT_CONNECTED

1592077753733 - 2020/06/13 14:49:13 - AudioPlayer : Destroying the audio players

1592077753733 - 2020/06/13 14:49:13 - MainActivity : Destroying
```

**Comment by XBigTK13X** [comment]
This is fixed with the new cast management.
