### ISSUE TITLE
Queuing up certain artists can cause a null crash

### ISSUE THREAD

**Issue by XBigTK13X** [XBigTK13X/snowgloo#63]
Happens when adding the Daniel Tiger albums from the Kids category.

```
1661787985934 - 2022/08/29 10:46:25 - MainActivity : ====== Starting new app instance ======

1661787985952 - 2022/08/29 10:46:25 - MainActivity : Resuming with intent null

1661787985947 - 2022/08/29 10:46:25 - AudioPlayer : Launching with the local player

1661787985946 - 2022/08/29 10:46:25 - CastPlayer : isCasting is false

1661787985983 - 2022/08/29 10:46:25 - SnowglooService : onStartCommand action=null

1661787985971 - 2022/08/29 10:46:25 - SnowglooService : onCreate()

1661787983262 - 2022/08/29 10:46:23 - Util : An error occurred Attempt to invoke virtual method
'int java.lang.Integer.intValue()' on a null object reference =>  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
at com.simplepathstudios.snowgloo.fragment.AddArtistToQueueDialogFragment$SortSongs.compare(AddArtistToQueueDialogFragment.java:47) 
at com.simplepathstudios.snowgloo.fragment.AddArtistToQueueDialogFragment$SortSongs.compare(AddArtistToQueueDialogFragment.java:31)
at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
at java.util.TimSort.sort(TimSort.java:234)
at java.util.Arrays.sort(Arrays.java:1492)
at java.util.ArrayList.sort(ArrayList.java:1470)
at java.util.Collections.sort(Collections.java:206)
at com.simplepathstudios.snowgloo.fragment.AddArtistToQueueDialogFragment$3.onClick(AddArtistToQueueDialogFragment.java:84)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:188)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8641)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

1661787972785 - 2022/08/29 10:46:12 - SnowglooService : onStartCommand action=null

1661787972774 - 2022/08/29 10:46:12 - SnowglooService : onCreate()
```

**Comment by XBigTK13X** [comment]
Seems fixed in the latest build. Might have been an issue in an underlying library that was updated.
